name: LaTeX Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -xelatex -shell-escape -output-directory=build -halt-on-error -pdf -interaction=nonstopmode
      - uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: build/main.pdf
