name: LaTeX Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Perl
        run: sudo apt-get install -y perl libyaml-tiny-perl libfile-homedir-perl
      - name: Clone latexindent.pl
        run: git clone https://github.com/cmhughes/latexindent.pl.git /tmp/latexindent.pl
      - run: git -C /tmp/latexindent.pl fetch --all --tags
      - name: Checkout the latest release
        run: git -C /tmp/latexindent.pl checkout V3.24.4
      - name: Check Format
        run: make LATEXINDENT="perl /tmp/latexindent.pl/latexindent.pl" check-fmt

  build:
    runs-on: ubuntu-22.04
    needs: check
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -xelatex -shell-escape -output-directory=build -halt-on-error -pdf -interaction=nonstopmode
          texlive_version: 2023
          extra_system_packages: "inkscape"
      - uses: actions/upload-artifact@v4
        id: artifact
        with:
          name: main-${{ github.sha }}.pdf
          path: build/main.pdf
      - uses: actions/upload-pages-artifact@v1
        if: github.ref == 'refs/heads/main'
        with:
          # location of the coverage artifacts
          path: "./build"

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/main.pdf
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
