name: LaTeX Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Perl
        run: sudo apt-get install -y perl libyaml-tiny-perl libfile-homedir-perl
      - name: Clone latexindent.pl
        run: git clone https://github.com/cmhughes/latexindent.pl.git /tmp/latexindent.pl
      - run: git -C /tmp/latexindent.pl fetch --all --tags
      - name: Checkout the latest release
        run: git -C /tmp/latexindent.pl checkout V3.24.4
      - name: Check Format
        run: make LATEXINDENT="perl /tmp/latexindent.pl/latexindent.pl" check-fmt

  build:
    runs-on: ubuntu-22.04
    needs: check
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -xelatex -shell-escape -output-directory=build -halt-on-error -pdf -interaction=nonstopmode
          texlive_version: 2023
      - uses: actions/upload-artifact@v4
        with:
          name: main-${{ github.sha }}.pdf
          path: build/main.pdf
